# Database connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/insta_app

# Database username and password
spring.datasource.username=root
spring.datasource.password=Siva@1998

# JDBC driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialect for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Automatically update schema (use cautiously in production)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL output for readability
spring.jpa.properties.hibernate.format_sql=true